CREATE TABLE `candidates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `election_yr` smallint(6) DEFAULT NULL,
  `lin_ima` text,
  `can_id` varchar(9) DEFAULT NULL,
  `can_nam` varchar(90) DEFAULT NULL,
  `can_off` varchar(1) DEFAULT NULL,
  `can_off_sta` varchar(2) DEFAULT NULL,
  `can_off_dis` varchar(2) DEFAULT NULL,
  `can_par_aff` varchar(3) DEFAULT NULL,
  `can_inc_cha_ope_sea` varchar(255) DEFAULT NULL,
  `can_str1` text,
  `can_str2` text,
  `can_cit` text,
  `can_sta` varchar(2) DEFAULT NULL,
  `can_zip` varchar(9) DEFAULT NULL,
  `ind_ite_con` decimal(15,2) DEFAULT NULL,
  `ind_uni_con` decimal(15,2) DEFAULT NULL,
  `ind_con` decimal(15,2) DEFAULT NULL,
  `par_com_con` decimal(15,2) DEFAULT NULL,
  `oth_com_con` decimal(15,2) DEFAULT NULL,
  `can_con` decimal(15,2) DEFAULT NULL,
  `tot_con` decimal(15,2) DEFAULT NULL,
  `tra_fro_oth_aut_com` decimal(15,2) DEFAULT NULL,
  `can_loa` decimal(15,2) DEFAULT NULL,
  `oth_loa` decimal(15,2) DEFAULT NULL,
  `tot_loa` decimal(15,2) DEFAULT NULL,
  `off_to_ope_exp` decimal(15,2) DEFAULT NULL,
  `off_to_fun` decimal(15,2) DEFAULT NULL,
  `off_to_leg_acc` decimal(15,2) DEFAULT NULL,
  `oth_rec` decimal(15,2) DEFAULT NULL,
  `tot_rec` decimal(15,2) DEFAULT NULL,
  `ope_exp` decimal(15,2) DEFAULT NULL,
  `exe_leg_acc_dis` decimal(15,2) DEFAULT NULL,
  `fun_dis` decimal(15,2) DEFAULT NULL,
  `tra_to_oth_aut_com` decimal(15,2) DEFAULT NULL,
  `can_loa_rep` decimal(15,2) DEFAULT NULL,
  `oth_loa_rep` decimal(15,2) DEFAULT NULL,
  `tot_loa_rep` decimal(15,2) DEFAULT NULL,
  `ind_ref` decimal(15,2) DEFAULT NULL,
  `par_com_ref` decimal(15,2) DEFAULT NULL,
  `oth_com_ref` decimal(15,2) DEFAULT NULL,
  `tot_con_ref` decimal(15,2) DEFAULT NULL,
  `oth_dis` decimal(15,2) DEFAULT NULL,
  `tot_dis` decimal(15,2) DEFAULT NULL,
  `cas_on_han_beg_of_per` decimal(15,2) DEFAULT NULL,
  `cas_on_han_clo_of_per` decimal(15,2) DEFAULT NULL,
  `net_con` decimal(15,2) DEFAULT NULL,
  `net_ope_exp` decimal(15,2) DEFAULT NULL,
  `deb_owe_by_com` decimal(15,2) DEFAULT NULL,
  `deb_owe_to_com` decimal(15,2) DEFAULT NULL,
  `cov_sta_dat` date DEFAULT NULL,
  `cov_end_dat` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_candidates_on_election_yr_and_can_id` (`election_yr`,`can_id`),
  KEY `index_candidates_on_election_yr` (`election_yr`),
  KEY `index_candidates_on_can_id` (`can_id`),
  KEY `index_candidates_on_can_nam` (`can_nam`),
  KEY `index_candidates_on_can_off_sta` (`can_off_sta`)
) ENGINE=InnoDB AUTO_INCREMENT=2511 DEFAULT CHARSET=utf8;

CREATE TABLE `races` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `election_yr` smallint(6) DEFAULT NULL,
  `can_id` varchar(9) DEFAULT NULL,
  `on_ballot` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_races_on_election_yr_and_can_id` (`election_yr`,`can_id`),
  KEY `index_races_on_election_yr` (`election_yr`),
  KEY `index_races_on_can_id` (`can_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE `schema_migrations` (
  `version` varchar(255) NOT NULL,
  UNIQUE KEY `unique_schema_migrations` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO schema_migrations (version) VALUES ('20140716130759');

INSERT INTO schema_migrations (version) VALUES ('20140807101832');